language: ruby
rvm:
  - 2.4.0
cache: bundler
services:
  - postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database Sprouted_test;' -U postgres
- bundle exec rake db:migrate
script: bundle exec rspec
